name: recipe_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ✅ Latest Firebase (all support firebase_core ^3.x)
  firebase_core: ^3.6.0
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.4.10

  # Image picker
  image_picker: ^1.1.2
  file_picker: ^8.0.7
  multi_image_picker_view: ^1.0.1

  # State management
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/biryani.png
    - assets/images/burger.png
    - assets/images/cake.png
    - assets/images/chola.png
    - assets/images/comboset.png
    - assets/images/frydishes.png
    - assets/images/indiandishe.png
    - assets/images/kachordishes.png
    - assets/images/nana.png
    - assets/images/ricedal.png
