// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKPyrdISJKGvi4W7w8y-R5wRk-ZY1fzd4',
    appId: '1:651275197600:web:5e52ff4b093ca9b2c8fdc5',
    messagingSenderId: '651275197600',
    projectId: 'receipe-app-76e10',
    authDomain: 'receipe-app-76e10.firebaseapp.com',
    storageBucket: 'receipe-app-76e10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8__1nW1etL6_Dzyoss8nYIMVz_Od4MCA',
    appId: '1:651275197600:android:9480f81d5c549eaac8fdc5',
    messagingSenderId: '651275197600',
    projectId: 'receipe-app-76e10',
    storageBucket: 'receipe-app-76e10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy_mtM-B9nxszgYIvpaoq-u0koAiXuJa8',
    appId: '1:651275197600:ios:6af9cc7fc7258d6fc8fdc5',
    messagingSenderId: '651275197600',
    projectId: 'receipe-app-76e10',
    storageBucket: 'receipe-app-76e10.firebasestorage.app',
    iosBundleId: 'com.example.receipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy_mtM-B9nxszgYIvpaoq-u0koAiXuJa8',
    appId: '1:651275197600:ios:6af9cc7fc7258d6fc8fdc5',
    messagingSenderId: '651275197600',
    projectId: 'receipe-app-76e10',
    storageBucket: 'receipe-app-76e10.firebasestorage.app',
    iosBundleId: 'com.example.receipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKPyrdISJKGvi4W7w8y-R5wRk-ZY1fzd4',
    appId: '1:651275197600:web:5e52ff4b093ca9b2c8fdc5',
    messagingSenderId: '651275197600',
    projectId: 'receipe-app-76e10',
    authDomain: 'receipe-app-76e10.firebaseapp.com',
    storageBucket: 'receipe-app-76e10.firebasestorage.app',
  );

}